AWSTemplateFormatVersion: "2010-09-09" 
Description: Cloudformation template file to create DynamoDB table
Resources: 
        myDynamoDBTable:
        Type: AWS::DynamoDB::Table 
        Properties: 
            TableName: :"2xsfnv-ck529-UCDP-CustomerPreferences-table"
            AttributeDefinitions: 
                - AttributeName: "AcctId"
                  AttributeType: "S" 
                - AttributeName: "ContractAcctId" 
                  AttributeType: "S" 
                - AttributeName: "Email" 
                  AttributeType: "S" 
                - AttributeName: "Phone"
                  AttributeType: "S" 
                - AttributeName: "CompanyCode" 
                  AttributeType: "S" 
                - AttributeName: "LOB" 
                  AttributeType: "S"
            KeySchema:
                - AttributeName: "AcctId" 
                  KeyType: "HASH" 
                - AttributeName: "ContractAcctId" 
                  KeyType: "RANGE"
            ProvisionedThroughput: 
                ReadCapacityUnits: "5" 
                WriteCapacityUnits: "5" 
        
        LocalSecondaryIndexes: 
                - IndexName: "CompanyCodeLSI" 
                  KeySchema:
                    - AttributeName: "AcctId" 
                      KeyType: "HASH" 
                    - AttributeName: "CompanyCode" 
                      KeyType: "RANGE"
                  Projection:
                     ProjectionType: "ALL"
                - IndexName: "LOBLSI" 
                  KeySchema:
                    - AttributeName: "AcctId" 
                      KeyType: "HASH" 
                    - AttributeName: "LOB" 
                      KeyType: "RANGE"
                  Projection:
                    ProjectionType: "ALL"
        
        GlobalSecondaryIndexes: 
                - IndexName: "GSI_Email_CAcct" 
                  KeySchema: 
                    - AttributeName: "Email" 
                      KeyType: "HASH" 
                    - AttributeName: "ContractAcctId" 
                      KeyType: "RANGE" 
                  Projection:
                    ProjectionType: "ALL"            
                  ProvisionedThroughput: 
                    ReadCapacityUnits: "5" 
                    WriteCapacityUnits: "5" 
                    
                - IndexName: "GSI_Phone_CAcct" 
                  KeySchema: 
                    - AttributeName: "ContractAcctId" 
                      KeyType: "HASH" 
                    - AttributeName: "Phone" 
                      KeyType: "RANGE" 
                  Projection:
                    ProjectionType: "ALL"
                  ProvisionedThroughput: 
                    ReadCapacityUnits: "5" 
                    WriteCapacityUnits: "5" 


Outputs:
  DynamoDBTableName:
    Value: !Ref 2xsfnv-ck529-UCDP-CustomerPreferences-table
