AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template to create DynamoDB table
Resources:
  myDynamoDBTable: 
    Type: 'AWS::DynamoDB::Table'
    Properties: 
      TableName: '2xsfnv-ck529-UCDP-CustomerPreferences-table'
      AttributeDefinitions:
        - AttributeName: AcctId
          AttributeType: S
        - AttributeName: ContractAcctId
          AttributeType: S
        - AttributeName: Email
          AttributeType: S
        - AttributeName: Phone
          AttributeType: S
        - AttributeName: CompanyCode
          AttributeType: S
        - AttributeName: LOB
          AttributeType: S
      KeySchema:
        - AttributeName: AcctId
          KeyType: HASH
        - AttributeName: ContractAcctId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      GlobalSecondaryIndexes:
        - IndexName: GSI_Email_CAcct
          KeySchema:
            - AttributeName: Email
              KeyType: HASH
            - AttributeName: ContractAcctId
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: '5'
            WriteCapacityUnits: '5'
          Projection:
            ProjectionType: ALL
        - IndexName: GSI_Phone_CAcct
          KeySchema:
            - AttributeName: Phone
              KeyType: HASH
            - AttributeName: ContractAcctId
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: '5'
            WriteCapacityUnits: '5'
          Projection:
            ProjectionType: ALL
      LocalSecondaryIndexes:
        - IndexName: LSI_CompanyCode
          KeySchema:
            - AttributeName: AcctId
              KeyType: HASH
            - AttributeName: CompanyCode
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: LSI_LOB
          KeySchema:
            - AttributeName: AcctId
              KeyType: HASH
            - AttributeName: LOB
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
Outputs:
  DynamoDBTableName:
    Value: !Ref myDynamoDBTable
