AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template file to create DynamoDB table
Resources:
  myDynamoDBTable: 
    Type: 'AWS::DynamoDB::Table'
    Properties: 
      TableName: '2xsfnv-ck529-UCDP-CustomerInteractions-table'
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: InteractionDt
          AttributeType: S
        - AttributeName: Intent
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      GlobalSecondaryIndexes:
        - IndexName: GSI_Basic
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: InteractionDt
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: '5'
            WriteCapacityUnits: '5'
          Projection:
            ProjectionType: ALL
        - IndexName: GSI_Intent_DateRange
          KeySchema:
            - AttributeName: Intent
              KeyType: HASH
            - AttributeName: InteractionDt
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: '5'
            WriteCapacityUnits: '5'
          Projection:
            ProjectionType: ALL

  MyLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaS3DynamoDBPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                  - 'dynamodb:PutItem'
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
  MyLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'DataIngestionLambda_CFV4'
      Handler: 'lambda_function.handler'
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Code:
        ZipFile: | 
      Runtime: 'python3.12'
      Timeout: 900
      Layers:
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python312:13

    
Outputs:
  DynamoDBTableName:
    Value: !Ref myDynamoDBTable
